basePath: /
host: localhost:3000
info:
  contact: {}
  description: 'HW #4'
  termsOfService: http://swagger.io/terms/
  title: 04.API-Product-Store-with-Mongo
  version: "0.2"
paths: {}
schemes:
- http
swagger: "2.0"
